### ISSUE TITLE
404 not found URL

### ISSUE THREAD

**Issue by tareqhassan** [elindydotcom/eddsumo#4]
After publishing the product, the current landing page URL is showing 404. Note that, the current EDD is version 3.0. 

Any reason behind that 404?

**Comment by elindydotcom** [comment]
Hi - as mentioned in the readme file, the plugin has not been updated to work with EDD 3.x.

Sorry about that.  Maybe one day we'll update it but no time right now.

**Comment by tareqhassan** [comment]
No worries, I can figure it out and now working. BTW, thanks a lot for your nice contribution :)

**Comment by elindydotcom** [comment]
Glad to hear you got it working.  If you feel like sharing your changes you can submit a pull request and we can merge it in.

**Comment by tareqhassan** [comment]
Nothing major...I just need to clear the database table manually that this plugin generates and then reinstall it as a fresh install which fixed the 404 error for EDD 3.0+ update :)
